### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by josephtkim** [rodbinwa/prj-rev-bwfs-tea-cozy#7]
**Grade: Exceeds Expectations**

**Summary:** I think you did an excellent job with your project implementation, which exceeded expectations. The page design looked great and seemed to follow the provided layout and styling of the spec guideline. It is no small feat applying properties such as flex and relative sizing to make the page look good, so you should be proud! I think you also did a great job structuring your project folders and files, separating each file type in their appropriate folders. The code was also well formatted and structured, properly using elements and attributes when appropriate, and had great code readability. 

Some areas for improvement are for the page design - Try to add some spacing above each anchored section, so that when clicking on a nav link, the section title appears without being overlapped by the header section. Also, there was a slight margin around the page, which you can try to remove.

As a challenge, try to implement responsive design to the page. You can do this utilizing any method, such as using flex or a framework like Bootstrap. This is an important concept that can be a review or something new to learn. Based on your work so far, I think you are up to the challenge. Keep up the great work!

**Comment by rodbinwa** [comment]
@josephtkim 
Thanks for your feedback and review!!

-Rod
